-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 12:20:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema poems
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poems
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poems` DEFAULT CHARACTER SET utf8mb4 ;
USE `poems` ;

-- -----------------------------------------------------
-- Table `poems`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poems`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poems`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poems`.`Posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `post_content` VARCHAR(1000) NULL,
  `title` VARCHAR(45) NULL,
  `Users_user_id` INT NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_Posts_Users_idx` (`Users_user_id` ASC),
  CONSTRAINT `fk_Posts_Users`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `poems`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poems`.`Ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poems`.`Ratings` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `Comment` VARCHAR(120) NULL,
  `Ratingscol` VARCHAR(45) NULL,
  `Posts_post_id` INT NOT NULL,
  `Users_user_id` INT NOT NULL,
  PRIMARY KEY (`rating_id`),
  INDEX `fk_Ratings_Posts1_idx` (`Posts_post_id` ASC),
  INDEX `fk_Ratings_Users1_idx` (`Users_user_id` ASC),
  CONSTRAINT `fk_Ratings_Posts1`
    FOREIGN KEY (`Posts_post_id`)
    REFERENCES `poems`.`Posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ratings_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `poems`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
